// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yaedmdiwxtwuujeypjsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhZWRtZGl3eHR3dXVqZXlwanN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjIzMjAsImV4cCI6MjA2MzgzODMyMH0.V0EBmeiYmA0fdLRFXkCHjPQ9oMkZk4TEgFiIMVmjcvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);